trigger:
- production

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.0'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'dist'
    config_file_location: '/'
    skip_api_build: true
    skip_app_build: true
    azure_static_web_apps_api_token: '4057d1b26414655076640984fe99723a9eba0127b23922655e71e02bdd5009e91-330b7f5a-6c25-4452-975a-a373d5e00a46010100396'
    deployment_environment: 'Production'
