// export const environment = {
//   production: true,
//   signInAuth: "https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyDdIDmQFMIa3aXSnoudkf3At_zQ9faFs2k",
//   mediaKey: "DE3339BDDF8B5D1A6BD3D965D7CCB4B6A7234672505A0023485852397777D05E",
//   mediaAccessUrl: "https://admin.consolidus.com/ssadm/imageUpload.cfm",
//   customerList: "https://consolidus.azurewebsites.net/api/users",
//   customerList1: "https://consolidus.azurewebsites.net/api/auth",
//   customer: "https://consolidus.azurewebsites.net/api/user",
//   orders: "https://consolidus.azurewebsites.net/api/orders",
//   quotes: "https://consolidus.azurewebsites.net/api/quotes",
//   stores: "https://consolidus.azurewebsites.net/api/stores",
//   storeNewUrl: "https://consolidus-store.azurewebsites.net/api/stores",
//   storeNewUrlRapidBuild: "https://consolidus-store.azurewebsites.net/api/rapid_build",
//   products: "https://consolidus.azurewebsites.net/api/products",
//   dashboard: "https://consolidus.azurewebsites.net/api/main_dashboard",
//   royalties: "https://consolidus.azurewebsites.net/api/royalties",
//   storeProducts: "https://consolidus-store.azurewebsites.net/api/store_products",
//   system: "https://consolidus.azurewebsites.net/api/system",
//   flps: "https://consolidus.azurewebsites.net/api/flps",
//   catalog: "https://consolidus.azurewebsites.net/api/catalog",
//   admins: "https://consolidus.azurewebsites.net/api/consolidus/admin",
//   smartart: "https://consolidus.azurewebsites.net/api/smartart",
//   rapid_build: "https://consolidus.azurewebsites.net/api/rapidbuild",
//   import_export: "https://consolidus.azurewebsites.net/api/import_export",
//   order_manage: "https://consolidus.azurewebsites.net/api/order_manage",
//   smartcents: "https://consolidus.azurewebsites.net/api/smartcents",
//   vendors: "https://consolidus.azurewebsites.net/api/vendors",
//   reports: "https://consolidus.azurewebsites.net/api/reports",
//   campaignMedia: "https://assets.consolidus.com/globalAssets/Campaigns",
//   productMedia: "https://assets.consolidus.com/globalAssets/Products",
//   rapidBuildMedia: "https://assets.consolidus.com/globalAssets/rapidBuild",
//   supportTickets: "https://consolidusapi.azure-api.net/api/support_ticket",
//   storeMedia: "https://assets.consolidus.com/globalAssets/Stores",
//   assetsURL: "https://assets.consolidus.com/",
//   supportTeam:
//     "https://assets.consolidus.com/globalAssets/System/Defaults/SupportTeam/",
//   generalFilesPath: 'https://admin.consolidus.com/ssadm/getFiles.cfm?Key=DE3339BDDF8B5D1A6BD3D965D7CCB4B6A7234672505A0023485852397777D05E',
//   featureImage:
//     "https://assets.consolidus.com/globalAssets/Stores/featureImage/",
//   firebaseConfig: {
//     apiKey: "AIzaSyDdIDmQFMIa3aXSnoudkf3At_zQ9faFs2k",
//     authDomain: "consolidus-cinnova.firebaseapp.com",
//     projectId: "consolidus-cinnova",
//     storageBucket: "consolidus-cinnova.appspot.com",
//     messagingSenderId: "187396735094",
//     appId: "1:187396735094:web:4127587a84d92215ec1f57"
//   }
// }

export const environment = {
  production: true,
  signInAuth: "https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyDdIDmQFMIa3aXSnoudkf3At_zQ9faFs2k",
  mediaKey: "DE3339BDDF8B5D1A6BD3D965D7CCB4B6A7234672505A0023485852397777D05E",
  mediaAccessUrl: "https://admin.consolidus.com/ssadm/imageUpload.cfm",
  customerList: "https://consolidusapi.azure-api.net/users",
  customerList1: "https://consolidus-prod.azurewebsites.net/api/auth",
  customer: "https://consolidusapi.azure-api.net/user",
  orders: "https://consolidusapi.azure-api.net/orders",
  quotes: "https://consolidusapi.azure-api.net/quotes",
  stores: "https://consolidusapi.azure-api.net/stores",
  storeNewUrl: "https://consolidusapi.azure-api.net/stores-api/stores",
  storeNewUrlRapidBuild: "https://consolidusapi.azure-api.net/stores-api/rapid_build",
  products: "https://consolidusapi.azure-api.net/products",
  dashboard: "https://consolidusapi.azure-api.net/main_dashboard",
  royalties: "https://consolidusapi.azure-api.net/royalties",
  storeProducts: "https://consolidusapi.azure-api.net/stores-api/store_products",
  system: "https://consolidusapi.azure-api.net/system",
  flps: "https://consolidusapi.azure-api.net/flps",
  catalog: "https://consolidusapi.azure-api.net/catalog",
  admins: "https://consolidusapi.azure-api.net/consolidus/admin",
  smartart: "https://consolidusapi.azure-api.net/smartart",
  rapid_build: "https://consolidusapi.azure-api.net/rapidbuild",
  import_export: "https://consolidusapi.azure-api.net/import_export",
  order_manage: "https://consolidusapi.azure-api.net/order_manage",
  smartcents: "https://consolidusapi.azure-api.net/smartcents",
  vendors: "https://consolidusapi.azure-api.net/vendors",
  reports: "https://consolidusapi.azure-api.net/reports",
  campaignMedia: "https://assets.consolidus.com/globalAssets/Campaigns",
  productMedia: "https://assets.consolidus.com/globalAssets/Products",
  rapidBuildMedia: "https://assets.consolidus.com/globalAssets/rapidBuild",
  supportTickets: "https://consolidusapi.azure-api.net/support_ticket",
  storeMedia: "https://assets.consolidus.com/globalAssets/Stores",
  assetsURL: "https://assets.consolidus.com/",
  supportTeam:
    "https://assets.consolidus.com/globalAssets/System/Defaults/SupportTeam/",
  generalFilesPath: 'https://admin.consolidus.com/ssadm/getFiles.cfm?Key=DE3339BDDF8B5D1A6BD3D965D7CCB4B6A7234672505A0023485852397777D05E',
  featureImage:
    "https://assets.consolidus.com/globalAssets/Stores/featureImage/",
  firebaseConfig: {
    apiKey: "AIzaSyDdIDmQFMIa3aXSnoudkf3At_zQ9faFs2k",
    authDomain: "consolidus-cinnova.firebaseapp.com",
    projectId: "consolidus-cinnova",
    storageBucket: "consolidus-cinnova.appspot.com",
    messagingSenderId: "187396735094",
    appId: "1:187396735094:web:4127587a84d92215ec1f57"
  }
}