export const navigations = [
    {
        id: 2,
        title: 'Product Status',
        icon: 'heroicons_outline:status-online',
        route: 'status',
    },
    {
        id: 2,
        title: 'Name & Description',
        icon: 'mat_outline:edit_note',
        route: 'name-description',
    },
    {
        id: 3,
        title: 'Physics & Shipping',
        icon: 'mat_outline:local_shipping',
        route: 'physics-shipping',
    },
    {
        id: 4,
        title: 'Net Cost',
        icon: 'mat_outline:price_change',
        route: 'net-cost',
    },
    {
        id: 5,
        title: 'Imprints',
        icon: 'mat_outline:checklist',
        route: 'imprints',
    },
    {
        id: 6,
        title: 'Colors',
        icon: 'mat_outline:color_lens',
        route: 'colors',
    },
    {
        id: 24,
        title: 'Inventory',
        icon: 'heroicons_outline:archive',
        route: 'inventory',
    },
    {
        id: 7,
        title: 'Sizes',
        icon: 'heroicons_outline:arrows-expand',
        route: 'sizes',
    },
    {
        id: 8,
        title: 'Features',
        icon: 'mat_outline:checklist',
        route: 'features',
    },
    {
        id: 9,
        title: 'Pack & Accessories',
        icon: 'feather:package',
        route: 'pack-accessories',
    },
    {
        id: 10,
        title: 'Default Images',
        icon: 'mat_outline:image',
        route: 'default-images',
    },
    {
        id: 11,
        title: 'Default Margins',
        icon: 'mat_outline:margin',
        route: 'default-margins',
    },
    {
        id: 12,
        title: 'Video',
        icon: 'mat_outline:play_circle_filled',
        route: 'video',
    },
    {
        id: 13,
        title: 'Swatches',
        icon: 'mat_outline:image',
        route: 'swatches',
    },
    {
        id: 14,
        title: 'Artwork Template',
        icon: 'heroicons_outline:template',
        route: 'art-template',
    },
    {
        id: 15,
        title: 'Product Reviews',
        icon: 'mat_outline:reviews',
        route: 'product-reviews',
    },
    {
        id: 16,
        title: 'Dietary Information',
        icon: 'mat_outline:info',
        route: 'dietary-information',
    },
    {
        id: 17,
        title: 'Licensing Terms',
        icon: 'mat_outline:picture_in_picture',
        route: 'licensing-terms',
    },
    {
        id: 18,
        title: 'Warehouse Options',
        icon: 'mat_outline:house_siding',
        route: 'warehouse-options',
    },
    {
        id: 24,
        title: 'Product Quote',
        icon: 'mat_outline:house_siding',
        route: 'product-quote',
    },
    {
        id: 1,
        title: 'Store Versions',
        icon: 'mat_outline:sd_storage',
        route: 'store-versions',
    },
    {
        id: 19,
        title: 'Update History',
        icon: 'mat_outline:history',
        route: 'update-history',
    },
    {
        id: 20,
        title: 'Order History',
        icon: 'mat_outline:history',
        route: 'order-history',
    },
    {
        id: 21,
        title: 'Internal Notes',
        icon: 'mat_outline:speaker_notes',
        route: 'internal-notes',
    },
    {
        id: 22,
        title: 'Core Products',
        icon: 'mat_outline:group_work',
        route: 'core-products',
    },
    {
        id: 23,
        title: 'Duplicate',
        icon: 'heroicons_outline:duplicate',
        route: 'duplicate',
    },
    {
        id: 23,
        title: 'Remove Product',
        icon: 'heroicons_outline:trash',
        route: 'remove-product',
    }
];