export const navigations = [
    {
        id: 2,
        title: 'Pricing',
        icon: 'mat_outline:price_change',
        route: 'pricing',
    },
    {
        id: 3,
        title: 'Shipping',
        icon: 'mat_outline:local_shipping',
        route: 'shipping',
    },
    {
        id: 4,
        title: 'Store-Level Coop',
        icon: 'mat_outline:price_change',
        route: 'store-level-coop',
    },
    {
        id: 5,
        title: 'Categories',
        icon: 'mat_outline:checklist',
        route: 'categories',
    },
    {
        id: 6,
        title: 'Extrinsic Category',
        icon: 'mat_outline:category',
        route: 'extrinsic-category',
    },
    {
        id: 24,
        title: 'Special Description',
        icon: 'mat_outline:description',
        route: 'special-description',
    },
    {
        id: 7,
        title: 'Permalink',
        icon: 'heroicons_outline:arrows-expand',
        route: 'permalink',
    },
    {
        id: 8,
        title: 'Related Products',
        icon: 'mat_outline:checklist',
        route: 'related-products',
    },
    {
        id: 9,
        title: 'Product Options',
        icon: 'feather:package',
        route: 'product-options',
    },
    {
        id: 10,
        title: 'Royality Settings',
        icon: 'mat_outline:image',
        route: 'royality-settings',
    },
    {
        id: 11,
        title: 'Images',
        icon: 'mat_outline:image',
        route: 'images',
    },
    {
        id: 12,
        title: 'Video',
        icon: 'mat_outline:play_circle_filled',
        route: 'video',
    },
    {
        id: 13,
        title: 'Colors',
        icon: 'mat_outline:color_lens',
        route: 'colors',
    },
    {
        id: 14,
        title: 'Imprints',
        icon: 'heroicons_outline:template',
        route: 'imprints',
    },
    {
        id: 15,
        title: 'Virtual Proof Images',
        icon: 'mat_outline:broken_image',
        route: 'virtual-proof-images',
    },
    {
        id: 16,
        title: 'Product Reviews',
        icon: 'mat_outline:info',
        route: 'product-reviews',
    },
    {
        id: 17,
        title: 'Profit Calculator',
        icon: 'mat_outline:calculate',
        route: 'profit-calculator',
    },
    // {
    //     id: 18,
    //     title: 'Simulator',
    //     icon: 'mat_outline:house_siding',
    // },
    {
        id: 1,
        title: 'Update History',
        icon: 'mat_outline:history',
        route: 'update-history',
    },
    {
        id: 19,
        title: 'Master Product',
        icon: 'mat_outline:production_quantity_limits',
        route: 'master-product',
    },
    {
        id: 20,
        title: 'Store Versions',
        icon: 'mat_outline:history',
        route: 'store-versions',
    },
    {
        id: 21,
        title: 'Remove From Store',
        icon: 'heroicons_outline:trash',
        route: 'remove-from-store',
    }
];